export const data = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1673940945/Frame_48_wlu0wt.png",
    title: "Password Generator",
    subtitle: "Creates unique, secure passwords for online accounts.",
    language: "React + Tailwind",
    code: "Code",
    codeLink: "https://github.com/preshpi/password",
    viewLink: "https://password-preshpi.vercel.app/",
    view: "View Site",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1673941436/Speak-Better_dlvelq.png",
    title: "Speak Better",
    subtitle: "Corrects all grammar errors.",
    language: "React + Tailwind + NodeJs",
    code: "Code",
    codeLink: "https://github.com/workshopapps/grammarcheckerai.web",
    viewLink: "https://speakbetter.fun/",
    view: "View Site",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1673941634/Eval360-Know-your-Engineers_qft5uy.png",
    title: "Eval360",
    subtitle: "Tool for assessing the skills of engineers in an organisation.",
    language: "React + StyledComponents + PHP",
    code: "Code",
    codeLink: "https://github.com/workshopapps/engineerprofile360.web",
    viewLink: "https://eval360.app/",
    view: "View Site",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1675030839/MicroURL_vldrk4.png",
    title: "MicroURL",
    subtitle: "Tools for shorten Url",
    language: "React + Tailwind",
    code: "Code",
    codeLink: "https://github.com/preshpi/url_shortener",
    viewLink: "https://url-shortener-omega-liard.vercel.app/",
    view: "View Site",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1673983858/React-App_ewftyh.png",
    title: "Linktree",
    subtitle: "Tools for getting and sharing links of different websites",
    language: "React + Tailwind",
    code: "Code",
    codeLink: "https://github.com/preshpi/linktree",
    viewLink: "https://linktree-azure.vercel.app/",
    view: "View Site",
  },
];
