export const data = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1681796171/Pinterest_Clone___Home_o79avk.png",
    title: "mediaSurf",
    subtitle: "Get images and videos of your choice from mediaSurf.",
    language: "Next.js + Tailwind + pexels API",
    code: "Code",
    codeLink: "https://github.com/preshpi/pinterest-clon",
    viewLink: "https://mediasurff.netlify.app/",
    view: "View Site",

  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1675030839/MicroURL_vldrk4.png",
    title: "MicroURL",
    subtitle: "Tools for shorten Url",
    language: "React + Tailwind",
    code: "Code",
    codeLink: "https://github.com/preshpi/url_shortener",
    viewLink: "https://url-shortener-omega-liard.vercel.app/",
    view: "View Site",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1679850196/Regiz_-_Alpha_Digital_Technology_1_kwkghz.png",
    title: "Regiz website",
    code: "Code",
    subtitle:
      "A generation alpha technology project that focuses on digital documents minting, authentication, authentication analysis software, social networking.",
    language: "React + Tailwind + vite",
    viewLink: "https://regiz.io/",
    view: "View Site",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1681463578/FlairStyle___Home_1_wotksb.png",
    title: "FlairStyle",
    code: "Code",
    codeLink: "https://github.com/preshpi/commerce",
    subtitle: "Fashion E-commerce website",
    language: "Next.js + Tailwind + Commerce.js(cms)",
    viewLink: "https://flairstyle.vercel.app/",
    view: "View Site",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1673940945/Frame_48_wlu0wt.png",
    title: "Password Generator",
    subtitle: "Creates unique, secure passwords for online accounts.",
    language: "React + Tailwind",
    code: "Code",
    codeLink: "https://github.com/preshpi/password",
    viewLink: "https://password-preshpi.vercel.app/",
    view: "View Site",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1697973810/noteey_hb6czf.png",
    title: "Noteey",
    subtitle: "Note Taking Tool",
    language: "NextJs + Tailwind + TypeScript",
    view: "Coming soon",
  },
];
