export const data = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1673940945/Frame_48_wlu0wt.png",
    title: "Password Generator",
    subtitle: "Creates unique, secure passwords for online accounts.",
    language: "React + Tailwind",
    code: "Code",
    codeLink: "https://github.com/preshpi/password",
    viewLink: "https://password-preshpi.vercel.app/",
    view: "View Site",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1673941436/Speak-Better_dlvelq.png",
    title: "Speak Better",
    subtitle: "Corrects all grammar errors.",
    language: "React + Tailwind + NodeJs",
    code: "Code",
    codeLink: "https://github.com/workshopapps/grammarcheckerai.web",
    viewLink: "https://speakbetter.fun/",
    view: "View Site",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dgtc1iood/image/upload/v1673941634/Eval360-Know-your-Engineers_qft5uy.png",
    title: "Eval360",
    subtitle: "Tool for assessing the skills of engineers in an organisation.",
    language: "React + StyledComponents + PHP",
    code: "Code",
    codeLink: "https://github.com/workshopapps/engineerprofile360.web",
    viewLink: "https://eval360.app/",
    view: "View Site",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1675030839/MicroURL_vldrk4.png",
    title: "MicroURL",
    subtitle: "Tools for shorten Url",
    language: "React + Tailwind",
    code: "Code",
    codeLink: "https://github.com/preshpi/url_shortener",
    viewLink: "https://url-shortener-omega-liard.vercel.app/",
    view: "View Site",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1679850196/Regiz_-_Alpha_Digital_Technology_1_kwkghz.png",
    title: "Regiz",
    code: "Code",
    subtitle:
      "A generation alpha technology project that focuses on digital documents minting, authentication, authentication analysis software, social networking.",
    language: "React + Tailwind + vite",
    viewLink: "https://regiz.io/",
    view: "View Site",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1679850486/preshdev_mvgxyf.png",
    title: "preshDev",
    code: "Code",
    codeLink: "https://github.com/preshpi/portfolio_",
    subtitle: "My Portfolio website",
    language: "React + Tailwind + vite",
    viewLink: "https://preciousegwuenu.dev/",
    view: "View Site",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1681463578/FlairStyle___Home_1_wotksb.png",
    title: "FlairStyle",
    code: "Code",
    codeLink: "https://github.com/preshpi/commerce",
    subtitle: "Fashion E-commerce website",
    language: "Next.js + Tailwind + Commerce.js(cms)",
    viewLink: "https://flairstyle.vercel.app/",
    view: "View Site",
  },
];
